swagger: "2.0"
info:
  description: "Example app"
  version: "1.0.0"
tags:
  - name: "car"
  - name: "user"
    description: "Operations about user"
schemes:
  - "https"
  - "http"
paths:
  /car/find:
    post:
      tags:
        - "car"
      description: ""
      operationId: "find by..."
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - in: body
          name: CarUser
          schema:
            $ref: "#/definitions/CarUser"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Car"
        400:
          description: "Invalid status value"
definitions:
  Car:
    type: "object"
    required:
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  CarUser:
    type: "object"
    required:
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      gender:
        type: "string"
        enum:
          - "male"
          - "female"